import type { CatalogItem } from '@/types';

/**
 * Component catalog — system design building blocks.
 * Original 11 groups ported from .design-ref/data.jsx::NODE_CATALOG,
 * extended with: SignalR, Hangfire/consumer, vector DBs, observability stack,
 * compute primitives, security/auth, more queues/databases.
 */

export interface CatalogGroup {
  group: string;
  items: CatalogItem[];
}

export const CATALOG: CatalogGroup[] = [
  {
    group: 'Databases',
    items: [
      {
        type: 'postgres',
        group: 'Databases',
        label: 'PostgreSQL',
        description: 'Relational SQL · ACID',
        icon: 'postgres',
        tone: 'data',
        category: 'database',
        supportedProtocols: ['sql'],
        hasSchemaEditor: true,
      },
      {
        type: 'mysql',
        group: 'Databases',
        label: 'MySQL',
        description: 'Relational SQL',
        icon: 'mysql',
        tone: 'data',
        category: 'database',
        supportedProtocols: ['sql'],
        hasSchemaEditor: true,
      },
      {
        type: 'mongo',
        group: 'Databases',
        label: 'MongoDB',
        description: 'Document store',
        icon: 'mongo',
        tone: 'data',
        category: 'database',
        hasSchemaEditor: true,
      },
      {
        type: 'dynamo',
        group: 'Databases',
        label: 'DynamoDB',
        description: 'Key-value · AWS',
        icon: 'dynamo',
        tone: 'data',
        category: 'database',
        hasSchemaEditor: true,
      },
      {
        type: 'cassandra',
        group: 'Databases',
        label: 'Cassandra',
        description: 'Wide-column distributed',
        icon: 'database',
        tone: 'data',
        category: 'database',
        hasSchemaEditor: true,
      },
      {
        type: 'neo4j',
        group: 'Databases',
        label: 'Neo4j',
        description: 'Graph database',
        icon: 'database',
        tone: 'data',
        category: 'database',
        hasSchemaEditor: true,
      },
      {
        type: 'clickhouse',
        group: 'Databases',
        label: 'ClickHouse',
        description: 'Columnar OLAP',
        icon: 'database',
        tone: 'data',
        category: 'database',
        hasSchemaEditor: true,
      },
      {
        type: 'influx',
        group: 'Databases',
        label: 'InfluxDB',
        description: 'Time-series',
        icon: 'database',
        tone: 'data',
        category: 'database',
        hasSchemaEditor: true,
      },
    ],
  },
  {
    group: 'Caches',
    items: [
      {
        type: 'redis',
        group: 'Caches',
        label: 'Redis',
        description: 'In-memory KV · pub/sub',
        icon: 'redis',
        tone: 'cache',
        category: 'cache',
        supportedProtocols: ['redis'],
      },
      {
        type: 'memcache',
        group: 'Caches',
        label: 'Memcached',
        description: 'In-memory cache',
        icon: 'redis',
        tone: 'cache',
        category: 'cache',
      },
      {
        type: 'varnish',
        group: 'Caches',
        label: 'Varnish',
        description: 'HTTP reverse-proxy cache',
        icon: 'gateway',
        tone: 'cache',
        category: 'cache',
      },
    ],
  },
  {
    group: 'Messaging',
    items: [
      {
        type: 'kafka',
        group: 'Messaging',
        label: 'Kafka',
        description: 'Event streaming',
        icon: 'kafka',
        tone: 'queue',
        category: 'queue',
        supportedProtocols: ['kafka'],
      },
      {
        type: 'rabbit',
        group: 'Messaging',
        label: 'RabbitMQ',
        description: 'AMQP broker',
        icon: 'rabbit',
        tone: 'queue',
        category: 'queue',
        supportedProtocols: ['amqp'],
      },
      {
        type: 'sqs',
        group: 'Messaging',
        label: 'SQS',
        description: 'AWS managed queue',
        icon: 'rabbit',
        tone: 'queue',
        category: 'queue',
      },
      {
        type: 'nats',
        group: 'Messaging',
        label: 'NATS',
        description: 'Lightweight pub/sub',
        icon: 'kafka',
        tone: 'queue',
        category: 'queue',
      },
      {
        type: 'pulsar',
        group: 'Messaging',
        label: 'Pulsar',
        description: 'Multi-tenant streaming',
        icon: 'kafka',
        tone: 'queue',
        category: 'queue',
      },
      {
        type: 'mqtt',
        group: 'Messaging',
        label: 'MQTT Broker',
        description: 'IoT pub/sub',
        icon: 'kafka',
        tone: 'queue',
        category: 'queue',
        supportedProtocols: ['mqtt'],
      },
    ],
  },
  {
    group: 'APIs',
    items: [
      {
        type: 'rest',
        group: 'APIs',
        label: 'REST API',
        description: 'HTTP service',
        icon: 'api',
        tone: 'service',
        category: 'compute',
        supportedProtocols: ['rest'],
        hasApiEditor: true,
      },
      {
        type: 'graphql',
        group: 'APIs',
        label: 'GraphQL',
        description: 'Schema-first query API',
        icon: 'graphql',
        tone: 'service',
        category: 'compute',
        supportedProtocols: ['graphql'],
        hasApiEditor: true,
      },
      {
        type: 'grpc',
        group: 'APIs',
        label: 'gRPC',
        description: 'Proto · binary RPC',
        icon: 'grpc',
        tone: 'service',
        category: 'compute',
        supportedProtocols: ['grpc'],
        hasApiEditor: true,
      },
      {
        type: 'websocket',
        group: 'APIs',
        label: 'WebSocket',
        description: 'Bidirectional sockets',
        icon: 'api',
        tone: 'service',
        category: 'compute',
        supportedProtocols: ['websocket'],
        hasApiEditor: true,
      },
      {
        type: 'signalr',
        group: 'APIs',
        label: 'SignalR Hub',
        description: 'Real-time .NET hub',
        icon: 'api',
        tone: 'service',
        category: 'compute',
        supportedProtocols: ['signalr'],
        hasApiEditor: true,
      },
    ],
  },
  {
    group: 'Edge & Routing',
    items: [
      {
        type: 'gateway',
        group: 'Edge & Routing',
        label: 'API Gateway',
        description: 'Routing · auth · rate limit',
        icon: 'gateway',
        tone: 'edge',
        category: 'network',
        hasApiEditor: true,
      },
      {
        type: 'cdn',
        group: 'Edge & Routing',
        label: 'CDN',
        description: 'Edge cache · static assets',
        icon: 'cdn',
        tone: 'edge',
        category: 'network',
      },
      {
        type: 'lb',
        group: 'Edge & Routing',
        label: 'Load Balancer',
        description: 'L4/L7 traffic split',
        icon: 'gateway',
        tone: 'edge',
        category: 'network',
      },
      {
        type: 'mesh',
        group: 'Edge & Routing',
        label: 'Service Mesh',
        description: 'Istio · Linkerd · sidecars',
        icon: 'gateway',
        tone: 'edge',
        category: 'network',
      },
      {
        type: 'waf',
        group: 'Edge & Routing',
        label: 'WAF',
        description: 'Web app firewall',
        icon: 'gateway',
        tone: 'edge',
        category: 'network',
      },
      {
        type: 'dns',
        group: 'Edge & Routing',
        label: 'DNS',
        description: 'Name resolution',
        icon: 'cdn',
        tone: 'edge',
        category: 'network',
      },
    ],
  },
  {
    group: 'Storage & Search',
    items: [
      {
        type: 's3',
        group: 'Storage & Search',
        label: 'S3 / R2',
        description: 'Object storage',
        icon: 's3',
        tone: 'data',
        category: 'database',
      },
      {
        type: 'elastic',
        group: 'Storage & Search',
        label: 'Elasticsearch',
        description: 'Full-text search',
        icon: 'search',
        tone: 'data',
        category: 'database',
        hasSchemaEditor: true,
      },
      {
        type: 'meili',
        group: 'Storage & Search',
        label: 'Meilisearch',
        description: 'Typo-tolerant search',
        icon: 'search',
        tone: 'data',
        category: 'database',
        hasSchemaEditor: true,
      },
      {
        type: 'opensearch',
        group: 'Storage & Search',
        label: 'OpenSearch',
        description: 'AWS Elasticsearch fork',
        icon: 'search',
        tone: 'data',
        category: 'database',
        hasSchemaEditor: true,
      },
    ],
  },
  {
    group: 'AI / ML',
    items: [
      {
        type: 'llm',
        group: 'AI / ML',
        label: 'LLM Service',
        description: 'OpenAI · Anthropic · local',
        icon: 'llm',
        tone: 'ai',
        category: 'ai',
        hasApiEditor: true,
      },
      {
        type: 'vector',
        group: 'AI / ML',
        label: 'Vector DB',
        description: 'pgvector · Pinecone · Qdrant',
        icon: 'vector',
        tone: 'ai',
        category: 'ai',
        hasSchemaEditor: true,
      },
      {
        type: 'embed',
        group: 'AI / ML',
        label: 'Embeddings',
        description: 'Encoder service',
        icon: 'sparkles',
        tone: 'ai',
        category: 'ai',
        hasApiEditor: true,
      },
      {
        type: 'modelserver',
        group: 'AI / ML',
        label: 'Model Server',
        description: 'vLLM · Ollama · Triton',
        icon: 'llm',
        tone: 'ai',
        category: 'ai',
        hasApiEditor: true,
      },
      {
        type: 'feature',
        group: 'AI / ML',
        label: 'Feature Store',
        description: 'Feast · Tecton',
        icon: 'sparkles',
        tone: 'ai',
        category: 'ai',
        hasSchemaEditor: true,
      },
    ],
  },
  {
    group: 'Auth & Security',
    items: [
      {
        type: 'auth',
        group: 'Auth & Security',
        label: 'Auth Service',
        description: 'OAuth · OIDC · JWT',
        icon: 'auth',
        tone: 'service',
        category: 'auth',
        hasApiEditor: true,
      },
      {
        type: 'idp',
        group: 'Auth & Security',
        label: 'Identity Provider',
        description: 'Auth0 · Keycloak · Okta',
        icon: 'auth',
        tone: 'service',
        category: 'auth',
        hasApiEditor: true,
      },
      {
        type: 'vault',
        group: 'Auth & Security',
        label: 'Secrets Vault',
        description: 'HashiCorp Vault · AWS SM',
        icon: 'auth',
        tone: 'service',
        category: 'auth',
        hasApiEditor: true,
      },
    ],
  },
  {
    group: 'Compute',
    items: [
      {
        type: 'service',
        group: 'Compute',
        label: 'Microservice',
        description: 'Stateless service',
        icon: 'api',
        tone: 'service',
        category: 'compute',
        hasApiEditor: true,
      },
      {
        type: 'lambda',
        group: 'Compute',
        label: 'Lambda',
        description: 'Serverless function',
        icon: 'worker',
        tone: 'service',
        category: 'compute',
        hasApiEditor: true,
        hasConsumerEditor: true,
      },
      {
        type: 'container',
        group: 'Compute',
        label: 'Container',
        description: 'Docker · K8s pod',
        icon: 'api',
        tone: 'service',
        category: 'compute',
        hasApiEditor: true,
      },
      {
        type: 'edgefn',
        group: 'Compute',
        label: 'Edge Function',
        description: 'Cloudflare Worker · Vercel Edge',
        icon: 'worker',
        tone: 'service',
        category: 'compute',
        hasApiEditor: true,
      },
    ],
  },
  {
    group: 'Workers & Consumers',
    items: [
      {
        type: 'worker',
        group: 'Workers & Consumers',
        label: 'Background Worker',
        description: 'Async job runner',
        icon: 'worker',
        tone: 'ops',
        category: 'compute',
        hasConsumerEditor: true,
      },
      {
        type: 'cron',
        group: 'Workers & Consumers',
        label: 'Cron / Scheduler',
        description: 'Scheduled tasks',
        icon: 'worker',
        tone: 'ops',
        category: 'compute',
        hasConsumerEditor: true,
      },
      {
        type: 'hangfire',
        group: 'Workers & Consumers',
        label: 'Hangfire',
        description: '.NET background jobs',
        icon: 'worker',
        tone: 'ops',
        category: 'compute',
        hasConsumerEditor: true,
      },
      {
        type: 'kafka-consumer',
        group: 'Workers & Consumers',
        label: 'Kafka Consumer',
        description: 'Stream consumer group',
        icon: 'worker',
        tone: 'ops',
        category: 'compute',
        hasConsumerEditor: true,
      },
      {
        type: 'webhook',
        group: 'Workers & Consumers',
        label: 'Webhook Handler',
        description: 'Incoming HTTP callbacks',
        icon: 'worker',
        tone: 'ops',
        category: 'compute',
        hasApiEditor: true,
      },
    ],
  },
  {
    group: 'Observability',
    items: [
      {
        type: 'prometheus',
        group: 'Observability',
        label: 'Prometheus',
        description: 'Metrics scraper',
        icon: 'metrics',
        tone: 'ops',
        category: 'observability',
      },
      {
        type: 'grafana',
        group: 'Observability',
        label: 'Grafana',
        description: 'Dashboards · alerting',
        icon: 'metrics',
        tone: 'ops',
        category: 'observability',
      },
      {
        type: 'loki',
        group: 'Observability',
        label: 'Loki',
        description: 'Log aggregation',
        icon: 'metrics',
        tone: 'ops',
        category: 'observability',
      },
      {
        type: 'jaeger',
        group: 'Observability',
        label: 'Jaeger',
        description: 'Distributed tracing',
        icon: 'metrics',
        tone: 'ops',
        category: 'observability',
      },
      {
        type: 'sentry',
        group: 'Observability',
        label: 'Sentry',
        description: 'Error tracking',
        icon: 'metrics',
        tone: 'ops',
        category: 'observability',
      },
      {
        type: 'otel',
        group: 'Observability',
        label: 'OTel Collector',
        description: 'OpenTelemetry pipeline',
        icon: 'metrics',
        tone: 'ops',
        category: 'observability',
      },
    ],
  },
  {
    group: 'Clients',
    items: [
      {
        type: 'web',
        group: 'Clients',
        label: 'Web App',
        description: 'Browser client',
        icon: 'web',
        tone: 'client',
        category: 'client',
        hasMockupEditor: true,
      },
      {
        type: 'ios',
        group: 'Clients',
        label: 'iOS App',
        description: 'Native iOS',
        icon: 'ios',
        tone: 'client',
        category: 'client',
        hasMockupEditor: true,
      },
      {
        type: 'android',
        group: 'Clients',
        label: 'Android App',
        description: 'Native Android',
        icon: 'android',
        tone: 'client',
        category: 'client',
        hasMockupEditor: true,
      },
      {
        type: 'desktop',
        group: 'Clients',
        label: 'Desktop App',
        description: 'Electron · Tauri',
        icon: 'web',
        tone: 'client',
        category: 'client',
        hasMockupEditor: true,
      },
      {
        type: 'cli',
        group: 'Clients',
        label: 'CLI',
        description: 'Command-line tool',
        icon: 'web',
        tone: 'client',
        category: 'client',
      },
      {
        type: 'iot',
        group: 'Clients',
        label: 'IoT Device',
        description: 'Edge sensor / device',
        icon: 'web',
        tone: 'client',
        category: 'client',
      },
    ],
  },
  {
    group: 'External',
    items: [
      {
        type: 'stripe',
        group: 'External',
        label: 'Stripe',
        description: 'Payments',
        icon: 'stripe',
        tone: 'external',
        category: 'external',
      },
      {
        type: 'twilio',
        group: 'External',
        label: 'Twilio',
        description: 'SMS · voice',
        icon: 'stripe',
        tone: 'external',
        category: 'external',
      },
      {
        type: 'sendgrid',
        group: 'External',
        label: 'SendGrid',
        description: 'Transactional email',
        icon: 'stripe',
        tone: 'external',
        category: 'external',
      },
      {
        type: 's3-ext',
        group: 'External',
        label: 'External API',
        description: 'Third-party integration',
        icon: 'api',
        tone: 'external',
        category: 'external',
      },
    ],
  },
];

export const CATALOG_LOOKUP: Record<string, CatalogItem> = {};
for (const group of CATALOG) {
  for (const item of group.items) {
    CATALOG_LOOKUP[item.type] = item;
  }
}

export function findCatalogItem(type: string): CatalogItem | undefined {
  return CATALOG_LOOKUP[type];
}

export function searchCatalog(query: string): CatalogGroup[] {
  if (!query) return CATALOG;
  const q = query.toLowerCase();
  return CATALOG.map((g) => ({
    ...g,
    items: g.items.filter(
      (it) =>
        it.label.toLowerCase().includes(q) ||
        it.type.toLowerCase().includes(q) ||
        it.description.toLowerCase().includes(q),
    ),
  })).filter((g) => g.items.length > 0);
}
